name: iosApp
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    configFiles:
      Debug: Configuration/Debug.xcconfig
      Release: Configuration/Release.xcconfig
    sources:
      - path: iosApp
        excludes:
    resources:
      - path: iosApp/Assets.xcassets
      - path: iosApp/PrivacyInfo.xcprivacy
    info:
      path: iosApp/Info.plist
      properties:
        BGTaskSchedulerPermittedIdentifiers:
          - io.github.v2compose.auto-check-in
        CADisableMinimumFrameDurationOnPhone: true
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSPhotoLibraryAddUsageDescription: V2X 需要将图片保存到系统相册。
        UIApplicationSupportsIndirectInputEvents: true
        UIBackgroundModes:
          - fetch
        UILaunchScreen: { }
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON_NAME)
        SWIFT_VERSION: 5.0
        PRODUCT_NAME: $(APP_PRODUCT_NAME)
        PRODUCT_BUNDLE_IDENTIFIER: $(APP_BUNDLE_IDENTIFIER)
        INFOPLIST_FILE: iosApp/Info.plist
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        "EXCLUDED_ARCHS[sdk=iphonesimulator*]": x86_64
        TARGETED_DEVICE_FAMILY: 1
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
        OTHER_LDFLAGS:
          - $(inherited)
          - -ObjC
          - -framework
          - shared
    dependencies:
      - framework: ../shared/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/shared.framework
        embed: false
        codeSign: false
    preBuildScripts:
      - name: Build shared framework
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping Gradle build task invocation due to OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED environment variable set to \"YES\""
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :shared:embedAndSignAppleFrameworkForXcode \
            -Pcompose.ios.resources.platform="${PLATFORM_NAME:-$SDK_NAME}" \
            -Pcompose.ios.resources.archs="${NATIVE_ARCH_ACTUAL:-${ARCHS%% *}}"
